#!/bin/sh
echo "[Desktop Entry]
Categories=System;
Exec=java -jar /usr/bin/rsccfx.jar
Icon=rscc
Name=Remote Support
Name[de]=Fernwartung (JavaFX)
Name[en]=Remote Support (JavaFX)
Name[it]=Assistenza Remota (JavaFX)
StartupNotify=true
Type=Application" > /usr/share/applications/ch-imedias-rsccfx.desktop