package ch.imedias.rsccfx.model;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;

public class Rscc {
  /**
   * Points to the "docker-build_p2p" folder inside resources, relative to the build path.
   * Important: Make sure to NOT include a / in the beginning or the end.
   */
  private static final String PATH_TO_RESOURCE_DOCKER = "resources/docker-build_p2p";

  private final SystemCommander systemCommander;

  public Rscc(SystemCommander systemCommander) {
    this.systemCommander = systemCommander;
  }

  /**
   * Kills the connection to the keyserver.
   * @param key generated by requestKey().
   */
  public void killConnection(String key) {
    StringBuilder command = new StringBuilder();

    // Execute port_stop.sh with the generated key to kill the connection
    command.append("bash" + " " + PATH_TO_RESOURCE_DOCKER + "/");
    command.append("port_stop.sh" + " ");
    command.append(key);

    System.out.println(command.toString());

    systemCommander.executeTerminalCommand(command.toString());
  }
}
